#!/usr/bin/perl

use strict;
use warnings;

=head1 WORK IN PROGRESS

This script currently does nothing apart from basic param validation.

=cut

use Getopt::Long qw( GetOptions );
use Pod::Usage qw( pod2usage );
use File::Spec ();

our $VERSION = '0.001';
$VERSION = eval $VERSION;

my $secrets_file = File::Spec->catfile( $ENV{HOME}, '.secrets' );
my $show_help;
my @valid_actions = qw( list ls add edit delete print );

my $action;

GetOptions(
    'file=s' => \$secrets_file,
    'help|?' => \$show_help,
) or pod2usage();

$action = shift || pod2usage("Please specify an <action>");
pod2usage("Invalid <action> '$action'") unless grep { $_ eq $action } @valid_actions;

exit;

__END__
